### PR TITLE
did we ask?

### PR DESCRIPTION
**Pull request by tika**
no, we did not.

### CODE REVIEW

**Comment by robertt** [comment]
how much time did you spend on this

**Comment by tika** [comment]
LGTM!

**Comment by robertt** [comment]
blink twice if you're hurt

**Comment by tika** [comment]
> how much time did you spend on this

too long

**Review by robertt — CHANGES_REQUESTED** [review]
LGTM!

**Comment by tika** [comment]
Added HTML support!

**Comment by alii** [comment]
We didn't ask for this.

**Review by alii — APPROVED** [review]
LSTM (looks shit to me)

**Pull request merged**
